services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Admin123!
      - MYSQL_DATABASE=taskManagerSystem
      - MYSQL_USER=taskManagerAdmin
      - MYSQL_PASSWORD=Admin123!